spring:
  application:
    name: configserver-prod
  cloud:
    config:
      server:
        git:
          #basedir:
          uri: https://github.com/monkey9047/springcloudconfig.git
server:
  port: 9001
